### PR TITLE
Update fedora.yml

### PR DESCRIPTION
**Pull request by ghost**
Renaming from "Join" button to "Home".

### CODE REVIEW

**Comment by ralphbean** [comment]
Hm, I'm indifferent to this change.  I kind of liked having "Join" be the link back to the root of "what can I do for Fedora?".. but, if others chime in and really like renaming it to "Home", that works for me too.  Any opinions out there?

**Comment by pnemade** [comment]
I think "Home" makes more sense here instead of "Join". +1 for this PR.

**Comment by cydrobolt** [comment]
I agree, I also like "Home". It makes more sense in this context.

**Comment by ralphbean** [comment]
Let's do it!

**Pull request merged**
