### PR TITLE
Fix grammar: “its own”, not “it’s own”

### PR DESCRIPTION
**Pull request by fitojb**
http://its-not-its.info/

### CODE REVIEW

**Comment by cydrobolt** [comment]
@fitojb thanks for taking the time to file a pull request! I agree with you on changing "it's" to "its", but I am fairly sure the `.po` files are fetched from Zanata and not designed to be manually edited. 

Perhaps you'd like to file a new pull request or edit your current one with only your changes to `questions/includes/fedora/translation.yml` and `l10n/fedora/locale/asknot-ng.pot`?

**Comment by fitojb** [comment]
@cydrobolt Done!

**Comment by fitojb** [comment]
Is the commit correct now, @cydrobolt? :-)

**Comment by cydrobolt** [comment]
@fitojb sorry for the delay! Could you also remove the `.pot` file from the commit? It looks like that is also automatically generated. My mistake for not pointing it out earlier.

Thanks!

**Comment by fitojb** [comment]
@cydrobolt No worries, thank you for reviewing this! Now I’ve learned something about Zanata :-)

**Comment by ralphbean** [comment]
Nice!  Thanks both!

**Pull request merged**
