### PR TITLE
fixed error inside a docker container

### PR DESCRIPTION
**Pull request by hhlp**
The problem was the for some reason the docker container is accesing an old version of the site that why I've adjust ...

1. build.sh. remove -s options for static files.
2. I've remove references for images to workstation, server and cloud for message image not found.
3. adapt jquery and bootstrap for error about not using http over https.

Staging:

Captura de pantalla de 2021-11-27 18-46-39

Developer Branch under container:

Captura de pantalla de 2021-11-27 18-45-22

isolation:

Captura de pantalla de 2021-11-27 19-06-34

Regards.,

### CODE REVIEW

**Comment by hhlp** [comment]
It's seems I've forgoten to ping: @Zlopez , could you please review this PR...

Regards.,

**Comment by Zlopez** [comment]
@hhlp Could you look at the conflicts?

**Comment by hhlp** [comment]
> @hhlp Could you look at the conflicts?

@Zlopez   What conflict??? there is not conflict in this PR... I've resolved all the Log's messages...

Or Are you refering to this message:

```
.site-wrapper-inner {
  height: -webkit-calc(100% - 40px);
  height: -moz-calc(100% - 40px);
  height: calc(100% - 40px);
}
```

Regards.,

**Comment by Zlopez** [comment]
I can't merge this branch due to conflict. If you can rebase your branch to latest develop it would probably solve the conflict.

**Comment by hhlp** [comment]
@Zlopez  what is exactly the error did you get?

I don't see any conflict here, what I did?:

``` 
git clone git@github.com:fedora-infra/asknot-ng.git asknot-ng-conflict
git remote add upstream https://github.com/hhlp/asknot-ng.git
git pull upstream develop
```

``` 
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 35 (delta 17), reused 34 (delta 16), pack-reused 0
Desempaquetando objetos: 100% (35/35), 4.19 KiB | 1.40 MiB/s, listo.
Desde https://github.com/hhlp/asknot-ng
 * branch            develop    -> FETCH_HEAD
 * [nueva rama]      develop    -> upstream/develop
Actualizando a63a945..6b8cc88
Fast-forward
 Dockerfile                       |  2 +-
 build.sh                         |  3 +--
 l10n/fedora/locale/asknot-ng.pot |  2 +-
 questions/fedora.yml             |  4 ----
 templates/index.html             | 14 ++++++--------
 5 files changed, 9 insertions(+), 16 deletions(-)
``` 

Regards.,

**Comment by hhlp** [comment]
I'will make a new one

**Comment by Zlopez** [comment]
I can look into it and try to solve it if you want.

**Comment by hhlp** [comment]
@Zlopez no problem forget this one, I've maked a new one, you should not have any problem with this new one:

https://github.com/fedora-infra/asknot-ng/pull/158

Regards.,

**Pull request closed without merging**
