### PR TITLE
Extract translatable strings.

### PR DESCRIPTION
**Pull request by ralphbean**
Work in progress.  Making this thing translatable.

### CODE REVIEW

**Comment by ralphbean** [comment]
This branch is live up on http://whatcanidoforfedora.org where you can see the language switcher, although there's only one translation at the moment (english).

**Comment by cydrobolt** [comment]
I can set up ULS with asknot-ng, if you'd like. It is the same language selector that I used for getfedora.org (look at the bottom of the page)

**Comment by ralphbean** [comment]
Oo, that would be cool.  Can we do it in a separate PR after this one is merged?  I think the stuff in this one is all working as-is.

Does the code in this change set look okay?  Or is it nutty?  :stuck_out_tongue_winking_eye:

**Comment by cydrobolt** [comment]
The code doesn't look too bad, but it's a bit hard to understand :jack_o_lantern:

**Comment by ralphbean** [comment]
> it's a bit hard to understand

Good feedback.  I'll try to document it more thoroughly, then ping you back for another round of review if you don't mind.

**Comment by cydrobolt** [comment]
No problem

**Comment by ralphbean** [comment]
OK, @Cydrobolt.  After 6916cf2 it should be ready for another round of review.

**Comment by cydrobolt** [comment]
@ralphbean much better! :+1:

**Comment by ralphbean** [comment]
Woo!

**Pull request merged**
