### PR TITLE
fedora: Add fedora background image

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by sils** [comment]
And this is how it looks:

screenshot from 2015-08-15 20-42-02

**Comment by sils** [comment]
uhm there's a bug in there: background get's repeated.

**Comment by ralphbean** [comment]
That looks great.

**Comment by sils** [comment]
this is the new version: http://fedora.schuirmann.net/ with streched background.

**Comment by ralphbean** [comment]
:+1:  thanks!

**Pull request merged**
