### PR TITLE
add Fedora i18n

### PR DESCRIPTION
**Pull request by juhp**

### CODE REVIEW

**Comment by ralphbean** [comment]
Hi @juhp!  Thanks for this.

The L10n wiki page is actually already in the tree here:  https://github.com/juhp/asknot-ng/blob/patch-1/questions/includes/fedora/translation.yml#L5

I see no problem with adding it twice, but, did you see the other one first?  (It falls under "Translation" instead of "Internationalization").

**Comment by juhp** [comment]
Yes, I did, but i18n /= l10n. I did also ponder combining i18n into Translation but they are really as different technically as docs and programming.

**Comment by ralphbean** [comment]
> Yes, I did, but i18n /= l10n. I did also ponder combining i18n into Translation but they are really as different technically as docs and programming.

I had no idea.  Thank you!

**Comment by juhp** [comment]
But combining them might still be cleaner/simpler from the newcomer perspective... but then we should change the title from Translation.
Maybe we can do that later. :)

**Comment by ralphbean** [comment]
> Maybe we can do that later

Yes yes!  You know much more about it than I do.  Please re-organize it any way you think makes sense.  :)

**Pull request merged**
