### PR TITLE
coala: Add money interest to questions

### PR DESCRIPTION
**Pull request by sils**
Not sure if we really want that, I'd love to hear opinions on if this is a good thing.

### CODE REVIEW

**Comment by ralphbean** [comment]
Seems like a good idea to me (but I don't have much skin in the coala game).

**Comment by sils** [comment]
It's not really anything special to coala, is it? So if you're fine with this, go ahead and merge :)

**Comment by ralphbean** [comment]
Yay!  :ship: :money_with_wings: :moneybag:

**Comment by cydrobolt** [comment]
:money_with_wings:

**Pull request merged**
