### PR TITLE
Add coala question set

### PR DESCRIPTION
**Pull request by sils**
We're preparing to use asknot-ng for the coala code analysis framework. Our bits of contributions for now:
- A new question set
- You already got a few bug reports
- A theme will follow

### CODE REVIEW

**Comment by sils** [comment]
test instance is up on http://coala.schuirmann.net

**Comment by cydrobolt** [comment]
This is cool, but why are you trying to add this into the Fedora repo? You should fork this repository then add your own changes, since these changes are unrelated to fedora

**Comment by sils** [comment]
@Cydrobolt see https://github.com/fedora-infra/asknot-ng#contributing-back , this repo is not specific to fedora, fedora is just the only question set and theme available and happens to maintain it as far as I understand.

**Comment by cydrobolt** [comment]
Oops! You're right. Didn't realize that bit existed.

**Comment by ralphbean** [comment]
This is great!  Thanks @sils1297!  I'll give you commit rights on this repo so you can update things as needed.  We prefer that all changes still go through pull-request and review, but you're welcome to press the 'merge' button now after someone comments saying they think the change is sane.

:+1: to merge here.

**Comment by sils** [comment]
@ralphbean thanks, can I use WIP branches on this repo as well? Eases workflow.

**Comment by ralphbean** [comment]
> can I use WIP branches on this repo as well?

Please do.  That is best :)

**Comment by sils** [comment]
@ralphbean can I reach you on IRC or gitter interactively somewhere?

**Pull request merged**
