### PR TITLE
Add question for Fedora classroom

### PR DESCRIPTION
**Pull request by sanjayankur31**
Added snippet for Fedora classroom

### CODE REVIEW

**Review by bowlofeggs — APPROVED** [review]

**Comment by sanjayankur31** [comment]
thanks for the review @bowlofeggs - how would I go about getting wcidff regenerated with this now?

**Comment by bowlofeggs** [comment]
@sanjayankur31 I'm not familiar with wcidff - anyone else know the answer?

**Comment by sanjayankur31** [comment]
@ralphbean - apparently, I need to bug you for an update at the moment :D

**Comment by ralphbean** [comment]
I can do it!

**Comment by ralphbean** [comment]
Although, I have no merge rights.  @bowlofeggs - can you merge it?

**Pull request merged**
